Print the integration subunit results on error.

diff --git a/run-checks b/run-checks
--- a/run-checks
+++ b/run-checks
@@ -83,10 +83,15 @@ if [ -z "$QUICK" ]; then
     # integration suite in kvm
     if which adt-run >/dev/null 2>&1; then
         echo "Running integration tests on rolling edge"
-        go run _integration-tests/main.go --snappy-from-branch
+        result=0
+        go run _integration-tests/main.go --snappy-from-branch --filter searchSuite || result=$?
         # print the results.
         if which subunit2pyunit >/dev/null 2>&1; then
             subunit-1to2 /tmp/snappy-test/output/artifacts/results.subunit | subunit2pyunit
+        fi
+        if [ "$result" -ne 0 ]; then
+            echo "Integration tests failed"
+            exit $result
         fi
     fi
 fi
